### ISSUE TITLE
Addition for tracking commands

### ISSUE THREAD

**Issue by Raikeran** [pabletos/Hubot-Warframe#21]
Some suggestions I have for the /tracking commands. There should be a command that excludes all but select few track points without having to deselect every other point individually.
ex. /trackonly alerts_invasions_sorties

**Comment by TobiTenno** [comment]
how about just tracking and untracking all, @Raikeran?

**Comment by Raikeran** [comment]
That also works

**Comment by TobiTenno** [comment]
should be fixed with that pull request ( #22 )

**Comment by Raikeran** [comment]
Noice

**Comment by TobiTenno** [comment]
would you be up for closing it if that satisfies you?

**Comment by Raikeran** [comment]
yeah that's fine

**Comment by TobiTenno** [comment]
@Raikeran i can't close it, you have to
