### ISSUE TITLE
Conclave Challenge and Syndicate daily tracking options.

### ISSUE THREAD

**Issue by robertgk2017** [pabletos/Hubot-Warframe#38]
The bot can already check on both conclave challenges and the syndicate dailies, i just think it would be nice to have a tracking option for them.

**Comment by TobiTenno** [comment]
please make 2 seperate ones. the second is not possible.

**Comment by TobiTenno** [comment]
Completed with #39

**Comment by TobiTenno** [comment]
done on new bot, please close
