### ISSUE TITLE
Corrosive procs for armor stripping inaccurate

### ISSUE THREAD

**Issue by DeltaPhantom** [pabletos/Hubot-Warframe#40]
lib/_utils.js, line 39, Math.log should be Math.log10, per http://warframe.wikia.com/wiki/Damage_2.0/Corrosive_Damage#Complete_Armor_Depletion

**Comment by TobiTenno** [comment]
Thanks for the info. I know why now, but next time, if you include _why_ it's wrong, I'd appreciate it.

**Comment by TobiTenno** [comment]
fixed a long time ago, please close
